- Cargo.toml
- README.md
- examples/dyn_async_std.rs
- examples/dyn_tokio.rs
- examples/static.rs
- src/error.rs
- src/lib.rs
- src/rt_wrappers.rs
- src/static_pager.rs
- src/utils.rs
Fix #9.
This PR will, when done, introduce **breaking changes**: a major version will have to be released to avoid breaking user code (notably `pijul`).
Those breaking changes will be caused by the function now returning a `minus::Result` type
TODO LIST:
> Handle unused results

- Cargo.toml
I thought it would be easier to run the examples when cargo lists the required feature for each example on 'cargo run --example'
> Included feature requirements for examples in Cargo.toml

- src/init.rs
This detects if the line_count has just gone over the number of rows in the terminal, and draws if so.
Fixes scenarios where data doesnt get shown because more than one line (or more than the terminal height) get displayed.
Fixes #21.
> draw if the line_count has just overflowed the number of rows

- src/error.rs
- src/init.rs
- src/lib.rs
- src/utils.rs
As above,
This would be nice, for inclusion into the nushell ecosystem. Otherwise the paging makes the usability feel awkward (always paging). I tried doing this on nushell side, but this makes it alot easier & I was not able to get it working in the end the other way with async et al.
This still clears the screen each draw, but doesnt output all the other stuff, unless we have overflowed.
It may make more sense to have completely separate setup & cleanup sequences for each modes and:
if we over flow & page_if_havent_overflowed  == false, rerun setup which will clear the screen etc.
run different cleanup routines if we have overflowed, or not.
This also adds a data_finished() method, which flags to the system that data is no longer coming. This only makes sense when …
> Add ability to only engage the paging behaviour, if we have overflowed the screen rows

- Cargo.toml
- src/error.rs
- src/utils.rs
- src/utils/tests.rs
This upgrades to crossterm 0.19.0.
It also updates code which broke, due to different handling of ScrollUp & ScrollDown events in 0.19.0
> Upgrade crossterm

- src/utils.rs
This check only makes sense if we are setting up the screen for paging, therefore it should be inside of the check for setup_screen.
OK, this will be the last changes for a few days at least!
> move tty checking code inside of: if setup_screen {}

- src/init.rs
- src/lib.rs
- src/utils/tests.rs
This enables running callbacks, when the user exits from minus via pressing q & what not.
This is useful (essential!) when the other async data-producing code is possibly long running, and can be used to i.e. check for an exit variable shared via Arc<AtomicBool> within the data-producing async loop, to exit early.
I can add an example, to show how this works, as it may help understanding, and also for future users of the library, as the code is a little tricky.
> Add exit callback

- src/init.rs
- src/input/mod.rs
- src/lib.rs
- src/utils.rs
- src/utils/tests.rs
Add InputHandler trait which is settable on the pager struct, via set_input_handler(input_handler: Box<dyn InputHandler>)
Also add a DefaultInputHandler which handles input according to minus default, which is used by default.
The code which handles the internal minus Events, remains unchanged.
> Add InputHandler trait, to allow client code to define custom keybindings

- src/utils/tests.rs
Some of the tests assume that search is enabled.
This gates one of the parameters behind the search feature, allowing running tests without search functionality.
Unfortunately branch is based off of #33. Hopefully you accept that functionality. If not, I will create another pull request with this based off the main branch.
Thankyou.
> Fix tests without search

- README.md
- src/input/mod.rs
* Fixed keys j/k behaving in reverse
* Added half screen scrolling with behaviour similar to vim/less; from vim docs:
```
*CTRL-U*
CTRL-U          Scroll window Upwards in the buffer.  The number of
lines comes from the 'scroll' option (default: half a
screen).  If [count] given, first set the 'scroll'
option to [count].  The cursor is moved the same
number of lines up in the file (if possible; when
lines wrap and when hitting the end of the file there
may be a difference).  When the cursor is on the first
line of the buffer nothing happens and a beep is
produced.  See also 'startofline' option.
{difference from vi: Vim scrolls 'scroll' screen
lines, instead of file lines; makes a difference when
lines wrap}
```
```
*CTRL-D*
CTRL-D          Scroll window Downwards in the buffer.  The …
```
> Add half screen scroll keybindings

- src/static_pager.rs
Hi! Thanks for creating minus, such a great library!
Previously, setting `Pager.set_page_if_havent_overflowed(true)` had no effect if paging static output, due to an if condition in `static_pager.rs` which did not consider the setting. This commit makes this setting behave as expected when using a static reader.
As this commit only changes code so that it conforms to the documented behaviour, IMO this should only require a patch bump to the version :)
```rust
use minus::{page_all, Pager};
let p = Pager::new()
.set_page_if_havent_overflowed(true)
.set_text("Some short text");
page_all(p).unwrap();
```
**Previous behaviour**: "Some short text" is printed to stdout, with no paging.
**New behaviour in this commit**: "Some short text" is paged using minus.
Cheers!
> Fix set_page_if_havent_overflowed for static pager

- src/lib.rs
- src/search.rs
- src/tests.rs
To further improve performance, this does 3 things:
1. Adds more logic to `Pager::push_str` so that, instead of re-formatting everything when something new is pushed, it only re-formats and pushes what needs to be re-formatted.
2. Removes `Pager.wrap_lines` and `Pager.lines` and adds a new field (also called `lines`), that contains the entire text of what is shown on the screen, completely unformatted.
3. Moves the formatting logic that used to only be in `format_lines` into a new method, `Pager::formatted_line` so that both `push_str` and `format_lines` can access that logic when needed.
4. Removes an unnecessary vector clone in `format_lines` (it would clone `wrap_lines`, then clone each line of that when re-wrapping it. This now takes an iterator of `self.lines` and clones each line …
> Further improve performance, mainly in `Pager::push_str`

- src/dynamic_pager.rs
- src/lib.rs
This PR fixes missing feature docs from some functions like `dynamic_paging` and `set_tun_no_overflow`.
This did not work because it missed the `doc(...)` in `cfg_attr(docsrs, ...)` attribute.
> dynamic_paging: Fix missing doc(...) flag

- src/core/ev_handler.rs
- src/core/init.rs
- src/core/search.rs
- src/lib.rs
- src/tests.rs
This PR fixes two high severity bugs within `minus`
- Duplicity of  line numbers on appending str
This occurred because text takes the last line pushed into account from `PagerState::formatted_lines` which is as in the name itself formatted causing the line numbers to be displayed twice
- Pressing `n` does not takes to the next match
This occurred because `set_match_indices`  was sort of buggy with the new implementation of appending text
> Fix line numbers and search related bugs

- src/core/init.rs
In `start_reactor` (in `src/core/init.rs`), `RefCell`s are used unnecessarily so that the match arm closures can be declared as variables. However, if we don't declare these arms as variables and instead just insert them at the end of the match arms, we don't have to use refcells to store these variables. This also allows us to lock stdout (which is also implemented in this PR), which should make paging quicker and decrease flicker when scrolling quickly.
> Remove unnecessary refcell usage in start_reactor

- src/core/ev_handler.rs
- src/core/search.rs
Say you search for something and it has 10 matches, and you scroll down to the 10th. `pager.search_mark` would be equal to `9`. Then, you change the `search_term` to something that has only 5 matches. It will automatically call `search::next_match(p)`, which won't change anything, since `search_idx` only has 5 elements, but `search_mark` is 9. Then, if the user tries to go to the previous match, it will get `p.search_idx.iter().nth(p.search_mark).unwrap()`, which will cause a panic.
This fixes that by:
1. Resetting `p.search_mark` to 0 when you change the `search_term` so that it isn't something outside of the bounds
2. Changing `search::next_match` so that it doesn't depend on the current state of `ps.search_mark`, and instead just jumps to what is visually the next match.
3. Doesn't …
> Fix panic when changing search term

- src/state.rs
Should fix #69; untested, though.
> Format prompt when creating pager so that displayed_prompt is not empty

- src/state.rs
On 5.0.2, search doesn't work correctly when the match is in something other than the first displayed line of a matched line due to an off-by-one error. This fixes that.
> Fix searching issues after line number wrapping changes

- README.md
The README described the optional prefix of numbers before movement keys but due to the way markdown works, it was being treated as a HTML tag. This patch changes that so that it appears properly in the README.
> README: Fix optional n not appear before keys help

- src/state.rs
So sorry about this, but in #72 , I actually messed it up further since I change the wrong off-by-one thing. This actually fixes search in wrapped lines that do not have a line number, and I tested it many times to ensure that.
> Actually fix me messing up the off-by-one fix

- src/core/display/tests.rs
- src/lib.rs
- src/state.rs
on 5.0.2, lines that were wrapped while you had line numbers enabled would look like this:
```
1. This is a very long line yes
it is a very long line and it is a
continuation
2. And another line starts
here
```
This fixes it to look like this:
```
1. This is a very long line yes
it is a very long line and it is a
continuation
2. And another line starts
here
```
It also fixes tests to match this behavior and adds another test to catch if this regresses in the future.
> Align wrapped lines correctly where line number is omitted

- src/core/init.rs
- src/error.rs
In previous versions, during a panic the error message (and backtrace possibly) might not get displayed after a panic. This happened because
they were printed on the alternate screen and after the program exited, the terminal automatically switches to the main screen. hence
the message never gets to be displayed.
This patch fixes this by doing a cleanup before proceeding furthur on the unwinding of the panic
> init_core: Handle runtime panics better

- src/core/ev_handler.rs
- src/core/init.rs
- src/core/search.rs
- src/input/mod.rs
- src/lib.rs
The `q` or `Ctrl-c` command didn't properly quit the pager and didn't cleared the output in `PagerQuit` exit strategy. This occured because of redrawing after returning of the cleanup function. This patch fixes this performing the cleanup when the pager quits.
Closes #78
> bugfix: Regression in quitting in v5.0.4

- src/core/ev_handler.rs
- src/core/events.rs
- src/core/init.rs
For events that require immidiate screen update, which also includes a exit event, start_reactor check whether it is an exit event and avoids redrawing the screen and quits the pager
> init: Simplify screen cleanup code

- src/core/init.rs
Previously, if the pager was in `ExitStrategy::PagerQuit`, it would paint the pager one last time after receiving an exit event from the user, leaving junk on the screen.
As far as I can tell, the conditional changed in this patch was intended to avoid this extra paint, but had flipped &&/||, leading to this bug.
> Don't paint after processing exit events

- src/input/definitions/keydefs.rs
- src/input/definitions/mod.rs
- src/input/definitions/mousedefs.rs
- src/input/event_wrapper.rs
- src/input/mod.rs
This set of changes will allow minus to define key, mouse and resize
events to be declared natively through minus's APIs and not requiring end applications
to interact with the underlying crossterm crate.
This means that keybindings like Ctrl+L can be declared into minus like this
```rust
pager.add_input_event(KeyBind("c-l", |pagerstate| {
...
}));
```
**Note: Do note that this is not the final implementation and there will be large variations between this and the actual implementation that comes-up.**
This has the advantage that end-applications can now add to, modify, or remove minus's default event binding without needing
to copy the entire matcher function and then change the parts that they want.
This new API will not deprecate the previous way of defining input binding so existing …
> Introduce native input matching definition

- src/state.rs
End applications failed to compile when they copy pasted the default input::DefaultInputClassifier as the PagerState::message was not available at the public scope.
This patch fixes this by setting the item's scope to public
Closes #90
> fix(state): compile error due to message being private

- src/core/init.rs
Code setting RUNMODE was moved too far in 63328d02.
First, code checks if RUNMODE is static and only then it sets it to the selected mode. This way special cases when the stdout isn't a terminal or the output fits completely on the screen are not being hit.
> fix(init): Special static_output cases don't work

- .helix/languages.toml
- src/core/commands.rs
- src/core/ev_handler.rs
- src/core/init.rs
- src/input/mod.rs
- src/pager.rs
- src/state.rs
Closes https://github.com/arijit79/minus/issues/113
Closes https://github.com/arijit79/minus/issues/81
I haven't added any docs yet because I'm unsure how I can test it and I'd like to get some suggestions from you first, like if it's fine how I changed the code :)
> Feat: Add following mode

- flake.nix
- rust-toolchain.toml
Alright, this time it should work. rust-analyzer is added in the flake itself so you will not install rust-analyzer if you don't use the dev-shell from the flake.
> fix rust-toolchain of flake

- src/core/init.rs
@EiEddie can you test your code from this branch?. It will print out the events on the screen before handling them on the screen. This will help us investigate all the events that the event reader is reading.
> Investigate screen flickering on WSL/Windows Terminal

- src/core/commands.rs
- src/core/ev_handler.rs
- src/core/init.rs
- src/core/mod.rs
- src/core/utils/display/mod.rs
- src/state.rs
Many `Commands` is minus require additional operations to be done after their main objective have been completed. One example of this would be something like the `Search` command which after executing successfully also requires a update of the prompt to show the search match count. Currently all such commands directly use the functions handling these operations which makes the code look more confusing as well as introduces code duplication.
To solve this issue, a new type called `CommandQueue` is being introduced so that each`Ccommand` can issue other `Command`s to be executed once its main objective is finished executing. 
Although the implementation of this new type is mostly complete, we need to port all the `Command`s that require such cases to use this new type
> feat: Command queue

- flake.lock
- flake.nix
- rust-toolchain.toml
`rust-analyzer` doesn't work for me, because I also need `rust-src` but flakes `override` wipes the entries in the toolchain.
> adding "rust-src" to devShell

- src/pager.rs
Improves docs on the pager module andPager type
@TornaxO7 here we continue
>  Write more docs in the pager module

- src/core/utils/term.rs
While using [Jujutsu](https://github.com/martinvonz/jj) on Windows 10/11 in PowerShell, I discovered a bug that's very easy to fix. Whenever I enter the pager (for example with `jj log`) for the second time in a row, it fails to properly repaint. That's because the order of operations in `term::cleanup` is not exactly the inverse of `term::setup`. The problem is that the `EnableMouseCapture` command in crossterm stores the current mode and `DisableMouseCapture` restores it, so in effect it used to restore raw mode (which was enabled before enabling mouse capture) during cleanup after having disabled it.
I only observed this behavior in PowerShell so far, not `cmd.exe`. Maybe only PowerShell respects these accidentally mixed up mode settings between invocations while `cmd.exe` restores the …
> Fix order of mode restoration
